---
- name: Configuración básica de servidores
  hosts: servers
  become: yes
  tasks:
    - name: Actualizar caché de apt
      apt:
        update_cache: yes
        cache_valid_time: 3600  # Reduce el tiempo de validez del caché para evitar problemas en recursos limitados

    - name: Instalar Apache
      apt:
        name: apache2
        state: present
        install_recommends: no  # Evita la instalación de paquetes recomendados para reducir el uso de espacio

    - name: Instalar cowsay
      apt:
        name: cowsay
        state: present
        install_recommends: no  # Evita la instalación de paquetes recomendados para reducir el uso de espacio

    - name: Crear archivo en la máquina remota
      file:
        path: /home/vagrant/file.txt
        state: touch

    - name: Crear archivo en la máquina remota para copiar
      copy:
        content: "Contenido del archivo"
        dest: /home/vagrant/file.txt

    - name: Copiar archivo en la máquina remota
      copy:
        src: /home/vagrant/file.txt
        dest: /home/vagrant/file2.txt
        remote_src: yes 
        
    - name: Crear carpeta en la máquina remota
      file:
        path: /home/vagrant/folder
        state: directory

    - name: Iniciar servicio de Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Agregar usuario en la máquina remota
      user:
        name: nuevo_usuario
        state: present
        create_home: yes

    - name: Crear script en la máquina remota
      copy:
        content: |
          #!/bin/bash
          echo "Este es un script de prueba"
        dest: /home/vagrant/script.sh
        mode: '0755'

    - name: Ejecutar script en la máquina remota
      command: /home/vagrant/script.sh